using System;
using System.ComponentModel;
using System.Runtime.InteropServices;

namespace Synapse3.UserInteractive
{
    public class Win32PInvoke
    {
        [Description("SPI_(System-wide parameter - Used in SystemParametersInfo function )")]
        public enum SPI : uint
        {
            SPI_GETBEEP = 1u,
            SPI_SETBEEP = 2u,
            SPI_GETMOUSE = 3u,
            SPI_SETMOUSE = 4u,
            SPI_GETBORDER = 5u,
            SPI_SETBORDER = 6u,
            SPI_GETKEYBOARDSPEED = 10u,
            SPI_SETKEYBOARDSPEED = 11u,
            SPI_LANGDRIVER = 12u,
            SPI_ICONHORIZONTALSPACING = 13u,
            SPI_GETSCREENSAVETIMEOUT = 14u,
            SPI_SETSCREENSAVETIMEOUT = 0xFu,
            SPI_GETSCREENSAVEACTIVE = 0x10u,
            SPI_SETSCREENSAVEACTIVE = 17u,
            SPI_GETGRIDGRANULARITY = 18u,
            SPI_SETGRIDGRANULARITY = 19u,
            SPI_SETDESKWALLPAPER = 20u,
            SPI_SETDESKPATTERN = 21u,
            SPI_GETKEYBOARDDELAY = 22u,
            SPI_SETKEYBOARDDELAY = 23u,
            SPI_ICONVERTICALSPACING = 24u,
            SPI_GETICONTITLEWRAP = 25u,
            SPI_SETICONTITLEWRAP = 26u,
            SPI_GETMENUDROPALIGNMENT = 27u,
            SPI_SETMENUDROPALIGNMENT = 28u,
            SPI_SETDOUBLECLKWIDTH = 29u,
            SPI_SETDOUBLECLKHEIGHT = 30u,
            SPI_GETICONTITLELOGFONT = 0x1Fu,
            SPI_SETDOUBLECLICKTIME = 0x20u,
            SPI_SETMOUSEBUTTONSWAP = 33u,
            SPI_SETICONTITLELOGFONT = 34u,
            SPI_GETFASTTASKSWITCH = 35u,
            SPI_SETFASTTASKSWITCH = 36u,
            SPI_SETDRAGFULLWINDOWS = 37u,
            SPI_GETDRAGFULLWINDOWS = 38u,
            SPI_GETNONCLIENTMETRICS = 41u,
            SPI_SETNONCLIENTMETRICS = 42u,
            SPI_GETMINIMIZEDMETRICS = 43u,
            SPI_SETMINIMIZEDMETRICS = 44u,
            SPI_GETICONMETRICS = 45u,
            SPI_SETICONMETRICS = 46u,
            SPI_SETWORKAREA = 47u,
            SPI_GETWORKAREA = 48u,
            SPI_SETPENWINDOWS = 49u,
            SPI_GETHIGHCONTRAST = 66u,
            SPI_SETHIGHCONTRAST = 67u,
            SPI_GETKEYBOARDPREF = 68u,
            SPI_SETKEYBOARDPREF = 69u,
            SPI_GETSCREENREADER = 70u,
            SPI_SETSCREENREADER = 71u,
            SPI_GETANIMATION = 72u,
            SPI_SETANIMATION = 73u,
            SPI_GETFONTSMOOTHING = 74u,
            SPI_SETFONTSMOOTHING = 75u,
            SPI_SETDRAGWIDTH = 76u,
            SPI_SETDRAGHEIGHT = 77u,
            SPI_SETHANDHELD = 78u,
            SPI_GETLOWPOWERTIMEOUT = 79u,
            SPI_GETPOWEROFFTIMEOUT = 80u,
            SPI_SETLOWPOWERTIMEOUT = 81u,
            SPI_SETPOWEROFFTIMEOUT = 82u,
            SPI_GETLOWPOWERACTIVE = 83u,
            SPI_GETPOWEROFFACTIVE = 84u,
            SPI_SETLOWPOWERACTIVE = 85u,
            SPI_SETPOWEROFFACTIVE = 86u,
            SPI_SETCURSORS = 87u,
            SPI_SETICONS = 88u,
            SPI_GETDEFAULTINPUTLANG = 89u,
            SPI_SETDEFAULTINPUTLANG = 90u,
            SPI_SETLANGTOGGLE = 91u,
            SPI_GETWINDOWSEXTENSION = 92u,
            SPI_SETMOUSETRAILS = 93u,
            SPI_GETMOUSETRAILS = 94u,
            SPI_SETSCREENSAVERRUNNING = 97u,
            SPI_SCREENSAVERRUNNING = 97u,
            SPI_GETFILTERKEYS = 50u,
            SPI_SETFILTERKEYS = 51u,
            SPI_GETTOGGLEKEYS = 52u,
            SPI_SETTOGGLEKEYS = 53u,
            SPI_GETMOUSEKEYS = 54u,
            SPI_SETMOUSEKEYS = 55u,
            SPI_GETSHOWSOUNDS = 56u,
            SPI_SETSHOWSOUNDS = 57u,
            SPI_GETSTICKYKEYS = 58u,
            SPI_SETSTICKYKEYS = 59u,
            SPI_GETACCESSTIMEOUT = 60u,
            SPI_SETACCESSTIMEOUT = 61u,
            SPI_GETSERIALKEYS = 62u,
            SPI_SETSERIALKEYS = 0x3Fu,
            SPI_GETSOUNDSENTRY = 0x40u,
            SPI_SETSOUNDSENTRY = 65u,
            SPI_GETSNAPTODEFBUTTON = 95u,
            SPI_SETSNAPTODEFBUTTON = 96u,
            SPI_GETMOUSEHOVERWIDTH = 98u,
            SPI_SETMOUSEHOVERWIDTH = 99u,
            SPI_GETMOUSEHOVERHEIGHT = 100u,
            SPI_SETMOUSEHOVERHEIGHT = 101u,
            SPI_GETMOUSEHOVERTIME = 102u,
            SPI_SETMOUSEHOVERTIME = 103u,
            SPI_GETWHEELSCROLLLINES = 104u,
            SPI_SETWHEELSCROLLLINES = 105u,
            SPI_GETMENUSHOWDELAY = 106u,
            SPI_SETMENUSHOWDELAY = 107u,
            SPI_GETSHOWIMEUI = 110u,
            SPI_SETSHOWIMEUI = 111u,
            SPI_GETMOUSESPEED = 112u,
            SPI_SETMOUSESPEED = 113u,
            SPI_GETSCREENSAVERRUNNING = 114u,
            SPI_GETDESKWALLPAPER = 115u,
            SPI_GETACTIVEWINDOWTRACKING = 0x1000u,
            SPI_SETACTIVEWINDOWTRACKING = 4097u,
            SPI_GETMENUANIMATION = 4098u,
            SPI_SETMENUANIMATION = 4099u,
            SPI_GETCOMBOBOXANIMATION = 4100u,
            SPI_SETCOMBOBOXANIMATION = 4101u,
            SPI_GETLISTBOXSMOOTHSCROLLING = 4102u,
            SPI_SETLISTBOXSMOOTHSCROLLING = 4103u,
            SPI_GETGRADIENTCAPTIONS = 4104u,
            SPI_SETGRADIENTCAPTIONS = 4105u,
            SPI_GETKEYBOARDCUES = 4106u,
            SPI_SETKEYBOARDCUES = 4107u,
            SPI_GETMENUUNDERLINES = 4106u,
            SPI_SETMENUUNDERLINES = 4107u,
            SPI_GETACTIVEWNDTRKZORDER = 4108u,
            SPI_SETACTIVEWNDTRKZORDER = 4109u,
            SPI_GETHOTTRACKING = 4110u,
            SPI_SETHOTTRACKING = 4111u,
            SPI_GETMENUFADE = 4114u,
            SPI_SETMENUFADE = 4115u,
            SPI_GETSELECTIONFADE = 4116u,
            SPI_SETSELECTIONFADE = 4117u,
            SPI_GETTOOLTIPANIMATION = 4118u,
            SPI_SETTOOLTIPANIMATION = 4119u,
            SPI_GETTOOLTIPFADE = 4120u,
            SPI_SETTOOLTIPFADE = 4121u,
            SPI_GETCURSORSHADOW = 4122u,
            SPI_SETCURSORSHADOW = 4123u,
            SPI_GETMOUSESONAR = 4124u,
            SPI_SETMOUSESONAR = 4125u,
            SPI_GETMOUSECLICKLOCK = 4126u,
            SPI_SETMOUSECLICKLOCK = 4127u,
            SPI_GETMOUSEVANISH = 4128u,
            SPI_SETMOUSEVANISH = 4129u,
            SPI_GETFLATMENU = 4130u,
            SPI_SETFLATMENU = 4131u,
            SPI_GETDROPSHADOW = 4132u,
            SPI_SETDROPSHADOW = 4133u,
            SPI_GETBLOCKSENDINPUTRESETS = 4134u,
            SPI_SETBLOCKSENDINPUTRESETS = 4135u,
            SPI_GETUIEFFECTS = 4158u,
            SPI_SETUIEFFECTS = 4159u,
            SPI_GETFOREGROUNDLOCKTIMEOUT = 0x2000u,
            SPI_SETFOREGROUNDLOCKTIMEOUT = 8193u,
            SPI_GETACTIVEWNDTRKTIMEOUT = 8194u,
            SPI_SETACTIVEWNDTRKTIMEOUT = 8195u,
            SPI_GETFOREGROUNDFLASHCOUNT = 8196u,
            SPI_SETFOREGROUNDFLASHCOUNT = 8197u,
            SPI_GETCARETWIDTH = 8198u,
            SPI_SETCARETWIDTH = 8199u,
            SPI_GETMOUSECLICKLOCKTIME = 8200u,
            SPI_SETMOUSECLICKLOCKTIME = 8201u,
            SPI_GETFONTSMOOTHINGTYPE = 8202u,
            SPI_SETFONTSMOOTHINGTYPE = 8203u,
            SPI_GETFONTSMOOTHINGCONTRAST = 8204u,
            SPI_SETFONTSMOOTHINGCONTRAST = 8205u,
            SPI_GETFOCUSBORDERWIDTH = 8206u,
            SPI_SETFOCUSBORDERWIDTH = 8207u,
            SPI_GETFOCUSBORDERHEIGHT = 8208u,
            SPI_SETFOCUSBORDERHEIGHT = 8209u,
            SPI_GETFONTSMOOTHINGORIENTATION = 8210u,
            SPI_SETFONTSMOOTHINGORIENTATION = 8211u
        }

        [Flags]
        public enum SPIF
        {
            None = 0x0,
            SPIF_UPDATEINIFILE = 0x1,
            SPIF_SENDCHANGE = 0x2,
            SPIF_SENDWININICHANGE = 0x2
        }

        public const int WM_SETTINGCHANGE = 26;

        [DllImport("user32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool SystemParametersInfo(SPI uiAction, uint uiParam, IntPtr pvParam, SPIF fWinIni);
    }
}
